apiVersion: v1
kind: ServiceAccount
metadata:
  name: crik-node-state-server
  labels:
    app.kubernetes.io/name: crik-node-state-server
    app.kubernetes.io/part-of: crik
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crik-node-state-server
  labels:
    app.kubernetes.io/name: crik-node-state-server
    app.kubernetes.io/part-of: crik
rules:
  # Nodes
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crik-node-state-server
  labels:
    app.kubernetes.io/name: crik-node-state-server
    app.kubernetes.io/part-of: crik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crik-node-state-server
subjects:
  - kind: ServiceAccount
    name: crik-node-state-server
