apiVersion: v1
kind: Service
metadata:
  name: crik-node-state-server
spec:
  selector:
    app.kubernetes.io/name: crik-node-state-server
    app.kubernetes.io/part-of: crik
  ports:
    - protocol: TCP
      port: 9376
      targetPort: 9376
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crik-node-state-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: crik-node-state-server
      app.kubernetes.io/part-of: crik
  replicas: 3
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: main
      labels:
        app.kubernetes.io/name: crik-node-state-server
        app.kubernetes.io/part-of: crik
    spec:
      serviceAccountName: crik-node-state-server
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: main
          image: "{{ .Values.nodeStateServer.image.repository }}:{{ .Values.nodeStateServer.image.tag }}"
          command:
            - /manager
          args:
            - --metrics-port=8080
            - --health-probes-port=8081
            - --port=9376
            {{- if .Values.nodeStateServer.debug }}
            - --debug
            {{- end }}
          ports:
            # Exposes /nodes
            - name: main
              containerPort: 9376
              protocol: TCP
            # Exposes only /metrics
            - name: metrics
              containerPort: 8080
              protocol: TCP
            # Exposes /healthz and /readyz
            - name: probes
              containerPort: 8081
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      terminationGracePeriodSeconds: 10
